const regionMap = {
  'SMR-SN': {region: 'SMR-Southern Mindanao Region', district: 'SN-Sultan Kudarat North Cotabato'},
  'VR-CVD': {region: 'VR-Visayas Region', district: 'CVD-Central Visayas District'},
  'VR-EVD': {region: 'VR-Visayas Region', district: 'EVD-Eastern Visayas District'},
  'VR-ND': {region: 'VR-Visayas Region', district: 'ND-Negros District'},
  'VR-PD': {region: 'VR-Visayas Region', district: 'PD-Panay District'},
  'VR-DIST': {region: 'VR-Visayas Region'}
}

module.exports = {
  "VD-VISAYAS REGION": regionMap['VR-DIST'],
  "VD-CENTRAL VISAYAS DISTRICT": regionMap['VR-CVD'] ,
  "VD-EASTERN VISAYAS DISTRICT": regionMap['VR-EVD'] ,
  "VD-NEGROS ISLAND DISTRICT": regionMap['VR-ND'] ,
  "VD-PANAY ISLAND DISTRICT":  regionMap['VR-PD'],
  "VD-CEBU": regionMap['VR-CVD'],
  "VD-CEBU SOUTH BC": regionMap['VR-CVD'],
  "VD-CEBU TABUNOK BC": regionMap['VR-CVD'],
  "VD-CEBU CARCAR BC": regionMap['VR-CVD'],
  "VD-CARCAR": regionMap['VR-CVD'],
  "VD-MANDAUE CONSOLACION BC": regionMap['VR-CVD'],
  "VD-MANDAUE":regionMap['VR-CVD'] ,
  "VD-TOLEDO":regionMap['VR-CVD'] ,
  "VD-TAGBILARAN TUBIGON BC":regionMap['VR-CVD'] ,
  "VD-TAGBILARAN UBAY BC":regionMap['VR-CVD'] ,
  "VD-TAGBILARAN":regionMap['VR-CVD'] ,
  "VD-BOGO":regionMap['VR-CVD'] ,
  "VD-LAPU-LAPU":regionMap['VR-CVD'] ,
  "VD-CALBAYOG": regionMap['VR-EVD'] ,
  "VD-CALBAYOG CATARMAN BC": regionMap['VR-EVD'] ,
  "VD-CALBAYOG CATBALOGAN BC": regionMap['VR-EVD'] ,
  "VD-MAASIN": regionMap['VR-EVD'] ,
  "VD-MAASIN BAYBAY BC": regionMap['VR-EVD'] ,
  "VD-ORMOC": regionMap['VR-EVD'] ,
  "VD-ORMOC NAVAL BC": regionMap['VR-EVD'] ,
  "VD-ORMOC PALOMPON BC": regionMap['VR-EVD'] ,
  "VD-TACLOBAN": regionMap['VR-EVD'] ,
  "VD-TACLOBAN PALO BC": regionMap['VR-EVD'] ,
  "VD-TACLOBAN UBAY BC": regionMap['VR-EVD'] ,
  "VD-SOGOD": regionMap['VR-EVD'] ,
  "VD-BACOLOD": regionMap['VR-ND'],
  "VD-BACOLOD CADIZ BC": regionMap['VR-ND'] ,
  "VD-BACOLOD LA CARLOTA BC": regionMap['VR-ND'] ,
  "VD-BACOLOD SILAY BCO": regionMap['VR-ND'] ,
  "VD-DUMAGUETE": regionMap['VR-ND'] ,
  "VD-DUMAGUETE BAIS BC": regionMap['VR-ND'] ,
  "VD-DUMAGUETE BAYAWAN BC": regionMap['VR-ND'] ,
  "VD-KABANKALAN": regionMap['VR-ND'] ,
  "VD-KABANKALAN HINIGARAN BC": regionMap['VR-ND'] ,
  "VD-SAN CARLOS": regionMap['VR-ND'] ,
  "VD-ILOILO": regionMap['VR-PD'],
  "VD-ILOILO GUIMARAS BC": regionMap['VR-PD'],
  "VD-ILOILO JARO BC": regionMap['VR-PD'] ,
  "VD-ROXAS": regionMap['VR-PD'] ,
  "VD-ROXAS ESTANCIA BC": regionMap['VR-PD'] ,
  "VD-ROXAS PASSI BC": regionMap['VR-PD'] ,
  "VD-ANTIQUE": regionMap['VR-PD'] ,
  "VD-ANTIQUE CULASI BC": regionMap['VR-PD'] ,
  "VD-KALIBO": regionMap['VR-PD'] ,
  "VD-KALIBO CATICLAN BC": regionMap['VR-PD'] ,
}
